let name = "Mitch";
let age = 21;
let pnumber = 09091638067;
let email = "20216464@s.unaguio.edu";
let maddress = "Philex Mines";
let pr = "BSIT";
let idnum = 20216464;
let yrlvl = "First year"
let sctn = "IAA2";
document.getElementById("nm").innerHTML = name;
document.getElementById("ag").innerHTML = age;
document.getElementById("num").innerHTML = pnumber;
document.getElementById("em").innerHTML = email;
document.getElementById("madd").innerHTML = maddress;
document.getElementById("prog").innerHTML = pr;
document.getElementById("id").innerHTML = idnum;
document.getElementById("lvl").innerHTML = yrlvl;
document.getElementById("sec").innerHTML = sctn;